// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ross_Final.Models
{
    public partial class Driver
    {
        public Driver()
        {
            InfractionInfos = new HashSet<InfractionInfo>();
            Vehicles = new HashSet<Vehicle>();
        }

        public string DriverId { get; set; }
        public string DriverFirstName { get; set; }
        public string DriverLastName { get; set; }
        public string DriverSsn { get; set; }

        public virtual ICollection<InfractionInfo> InfractionInfos { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}