// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ross_Final.Models
{
    public partial class InfractionInfo
    {
        public string UsersId { get; set; }
        public string DriverId { get; set; }
        public string InfractionId { get; set; }
        public string VehicleId { get; set; }

        public virtual Driver Driver { get; set; }
        public virtual Infraction Infraction { get; set; }
        public virtual User Users { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}