// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ross_Final.Models
{
    public partial class Infraction
    {
        public Infraction()
        {
            InfractionInfos = new HashSet<InfractionInfo>();
        }

        public string InfractionId { get; set; }
        public string InfractionType { get; set; }

        public virtual ICollection<InfractionInfo> InfractionInfos { get; set; }
    }
}