// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ross_Final.Models
{
    public partial class User
    {
        public User()
        {
            InfractionInfos = new HashSet<InfractionInfo>();
        }

        public string UsersId { get; set; }
        public string UsersFirstName { get; set; }
        public string UsersLastName { get; set; }
        public string UsersEmployer { get; set; }
        public string UsesrUserName { get; set; }
        public string UsersPassword { get; set; }

        public virtual ICollection<InfractionInfo> InfractionInfos { get; set; }
    }
}