// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ross_Final.Models
{
    public partial class Vehicle
    {
        public Vehicle()
        {
            InfractionInfos = new HashSet<InfractionInfo>();
        }

        public string VehicleId { get; set; }
        public string DriverId { get; set; }
        public string VehicleLicensePlate { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }

        public virtual Driver Driver { get; set; }
        public virtual ICollection<InfractionInfo> InfractionInfos { get; set; }
    }
}