// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ross_Final.Models;

namespace ross_Final.Data
{
    public partial class DMVContext : DbContext
    {
        public DMVContext()
        {
        }

        public DMVContext(DbContextOptions<DMVContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Infraction> Infractions { get; set; }
        public virtual DbSet<InfractionInfo> InfractionInfos { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Driver>(entity =>
            {
                entity.ToTable("Driver");

                entity.Property(e => e.DriverId)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.DriverFirstName)
                    .IsRequired()
                    .HasMaxLength(52)
                    .IsUnicode(false);

                entity.Property(e => e.DriverLastName)
                    .IsRequired()
                    .HasMaxLength(52)
                    .IsUnicode(false);

                entity.Property(e => e.DriverSsn)
                    .IsRequired()
                    .HasMaxLength(11)
                    .IsUnicode(false)
                    .HasColumnName("DriverSSN");
            });

            modelBuilder.Entity<Infraction>(entity =>
            {
                entity.ToTable("Infraction");

                entity.Property(e => e.InfractionId)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.InfractionType)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<InfractionInfo>(entity =>
            {
                entity.HasKey(e => new { e.UsersId, e.DriverId, e.InfractionId, e.VehicleId });

                entity.ToTable("InfractionInfo");

                entity.Property(e => e.UsersId)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.DriverId)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.InfractionId)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.VehicleId)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.HasOne(d => d.Driver)
                    .WithMany(p => p.InfractionInfos)
                    .HasForeignKey(d => d.DriverId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_InfractionInfo_Driver");

                entity.HasOne(d => d.Infraction)
                    .WithMany(p => p.InfractionInfos)
                    .HasForeignKey(d => d.InfractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_InfractionInfo_Infraction");

                entity.HasOne(d => d.Users)
                    .WithMany(p => p.InfractionInfos)
                    .HasForeignKey(d => d.UsersId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_InfractionInfo_Users");

                entity.HasOne(d => d.Vehicle)
                    .WithMany(p => p.InfractionInfos)
                    .HasForeignKey(d => d.VehicleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_InfractionInfo_Vehicle");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.UsersId);

                entity.Property(e => e.UsersId)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.UsersEmployer)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.UsersFirstName)
                    .IsRequired()
                    .HasMaxLength(52)
                    .IsUnicode(false);

                entity.Property(e => e.UsersLastName)
                    .IsRequired()
                    .HasMaxLength(52)
                    .IsUnicode(false);

                entity.Property(e => e.UsersPassword)
                    .IsRequired()
                    .HasMaxLength(52)
                    .IsUnicode(false);

                entity.Property(e => e.UsesrUserName)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Vehicle>(entity =>
            {
                entity.ToTable("Vehicle");

                entity.Property(e => e.VehicleId)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.DriverId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.VehicleLicensePlate)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.VehicleMake)
                    .IsRequired()
                    .HasMaxLength(52)
                    .IsUnicode(false);

                entity.Property(e => e.VehicleModel)
                    .IsRequired()
                    .HasMaxLength(52)
                    .IsUnicode(false);

                entity.HasOne(d => d.Driver)
                    .WithMany(p => p.Vehicles)
                    .HasForeignKey(d => d.DriverId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Vehicle_Driver");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}